#!/usr/bin/env python3
"""
Configlet Builder
Generates Arista EOS configurations from Jinja2 templates and YAML variables
"""

import yaml
import json
from jinja2 import Environment, FileSystemLoader, select_autoescape
from pathlib import Path
import argparse
import sys
from datetime import datetime


class ConfigletBuilder:
    def __init__(self, template_dir='templates', variable_dir='variables', output_dir='output'):
        self.template_dir = Path(template_dir)
        self.variable_dir = Path(variable_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

        # Setup Jinja2 environment
        self.env = Environment(
            loader=FileSystemLoader(self.template_dir),
            autoescape=select_autoescape(),
            trim_blocks=True,
            lstrip_blocks=True
        )

        # Add custom filters
        self.env.filters['ip_network'] = self.ip_network_filter

    def load_variables(self, device_file, global_file='global-vars.yaml'):
        """Load device and global variables"""
        variables = {}

        # Load global variables
        global_path = self.variable_dir / global_file
        if global_path.exists():
            with open(global_path, 'r') as f:
                global_vars = yaml.safe_load(f)
                if global_vars:
                    variables.update(global_vars)

        # Load device-specific variables
        device_path = self.variable_dir / 'device-vars' / device_file
        with open(device_path, 'r') as f:
            device_vars = yaml.safe_load(f)
            if device_vars:
                variables.update(device_vars)

        return variables

    def render_template(self, template_name, variables):
        """Render a single template"""
        template = self.env.get_template(template_name)
        return template.render(**variables)

    def build_configlet(self, device_file, templates, output_file=None):
        """Build complete configlet from multiple templates"""
        variables = self.load_variables(device_file)

        configlet_parts = []
        configlet_parts.append("! " + "="*70)
        configlet_parts.append(f"! Configuration for {variables.get('hostname', 'UNKNOWN')}")
        configlet_parts.append(f"! Generated by Configlet Builder")
        configlet_parts.append(f"! Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        configlet_parts.append("! " + "="*70)
        configlet_parts.append("!")

        # Render each template
        for template in templates:
            try:
                rendered = self.render_template(template, variables)
                configlet_parts.append(rendered)
            except Exception as e:
                print(f"Error rendering {template}: {e}", file=sys.stderr)
                raise

        # Join all parts
        full_config = "\n".join(configlet_parts)

        # Write to file
        if output_file is None:
            output_file = f"{variables.get('hostname', 'device')}.cfg"

        output_path = self.output_dir / 'generated-configs' / output_file
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w') as f:
            f.write(full_config)

        print(f"✓ Generated: {output_path}")
        return output_path

    def build_bulk(self, device_list_file, templates):
        """Build configlets for multiple devices"""
        with open(device_list_file, 'r') as f:
            device_list = yaml.safe_load(f)

        for device in device_list['devices']:
            device_file = device['variable_file']
            output_file = device.get('output_file')

            try:
                self.build_configlet(device_file, templates, output_file)
            except Exception as e:
                print(f"✗ Failed to generate config for {device_file}: {e}", file=sys.stderr)

    @staticmethod
    def ip_network_filter(value):
        """Custom filter for IP network operations"""
        # Add ipaddress module operations if needed
        return value


def main():
    parser = argparse.ArgumentParser(description='Arista Configlet Builder')
    parser.add_argument('--device', '-d', help='Device variable file')
    parser.add_argument('--bulk', '-b', help='Bulk device list file')
    parser.add_argument('--templates', '-t', nargs='+', required=True, help='Template files to use')
    parser.add_argument('--output', '-o', help='Output filename')
    parser.add_argument('--template-dir', default='templates', help='Template directory')
    parser.add_argument('--variable-dir', default='variables', help='Variable directory')
    parser.add_argument('--output-dir', default='output', help='Output directory')

    args = parser.parse_args()

    builder = ConfigletBuilder(
        template_dir=args.template_dir,
        variable_dir=args.variable_dir,
        output_dir=args.output_dir
    )

    if args.bulk:
        builder.build_bulk(args.bulk, args.templates)
    elif args.device:
        builder.build_configlet(args.device, args.templates, args.output)
    else:
        print("Error: Must specify either --device or --bulk", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
