-- Migration: Add documentation and enrichment tables to CLI Browser
-- Purpose: Enable educational content, troubleshooting workflows, and enhanced command documentation
-- Date: 2026-01-21

-- ============================================================================
-- Command Documentation Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_command_docs (
    doc_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    short_description TEXT,              -- One-liner: "Configures BGP address family"
    long_description TEXT,                -- Detailed explanation (2-3 paragraphs)
    when_to_use TEXT,                     -- JSON array: use cases and scenarios
    privilege_level INTEGER DEFAULT 15,   -- Privilege level required (0-15)
    requires_config_mode BOOLEAN DEFAULT 1, -- Does it require config mode?
    tags TEXT,                            -- JSON array: ["BGP", "Routing", "IPv4"]
    ai_generated BOOLEAN DEFAULT 0,       -- Was this generated by AI?
    reviewed_by TEXT,                     -- Username of reviewer
    review_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE
);

CREATE INDEX idx_cmd_docs_command_id ON cli_command_docs(command_id);
CREATE INDEX idx_cmd_docs_tags ON cli_command_docs(tags);

-- ============================================================================
-- Parameter Documentation Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_parameter_docs (
    param_id INTEGER PRIMARY KEY AUTOINCREMENT,
    parameter_name TEXT NOT NULL,         -- "PREFIX", "ADDR_FAMILY", "ASN", etc.
    description TEXT NOT NULL,            -- "IPv4 prefix in CIDR notation"
    data_type TEXT,                       -- "ipv4-prefix", "integer", "string", "enum"
    valid_values TEXT,                    -- JSON array: ["ipv4 unicast", "ipv6 unicast"]
    value_range TEXT,                     -- "1-65535" for integers
    default_value TEXT,                   -- Default if not specified
    examples TEXT,                        -- JSON array: ["10.0.0.0/8", "192.168.1.0/24"]
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(parameter_name)
);

CREATE INDEX idx_param_docs_name ON cli_parameter_docs(parameter_name);

-- ============================================================================
-- Command Examples Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_command_examples (
    example_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    scenario TEXT NOT NULL,               -- "Configure eBGP neighbor"
    difficulty TEXT DEFAULT 'intermediate', -- "beginner", "intermediate", "advanced"
    workflow_steps TEXT NOT NULL,         -- JSON array of step objects
    expected_output TEXT,                 -- What you should see
    verification_commands TEXT,           -- JSON array of commands to verify
    explanation TEXT,                     -- Step-by-step breakdown
    use_case_category TEXT,               -- "Configuration", "Troubleshooting", "Monitoring"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE
);

CREATE INDEX idx_cmd_examples_command_id ON cli_command_examples(command_id);
CREATE INDEX idx_cmd_examples_difficulty ON cli_command_examples(difficulty);
CREATE INDEX idx_cmd_examples_category ON cli_command_examples(use_case_category);

-- ============================================================================
-- Troubleshooting Workflows Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_workflows (
    workflow_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,                  -- "BGP Neighbor Not Establishing"
    problem_description TEXT NOT NULL,    -- Detailed problem statement
    category TEXT NOT NULL,               -- "BGP", "Interface", "OSPF", "Performance"
    subcategory TEXT,                     -- "Connectivity", "Configuration", "Performance"
    severity TEXT DEFAULT 'warning',      -- "critical", "warning", "info"
    prerequisites TEXT,                   -- JSON array: what to check first
    estimated_time TEXT,                  -- "5-10 minutes"
    skill_level TEXT DEFAULT 'intermediate', -- "beginner", "intermediate", "advanced"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workflows_category ON cli_workflows(category);
CREATE INDEX idx_workflows_severity ON cli_workflows(severity);

-- ============================================================================
-- Workflow Steps Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_workflow_steps (
    step_id INTEGER PRIMARY KEY AUTOINCREMENT,
    workflow_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    step_title TEXT NOT NULL,             -- "Check BGP summary"
    mode_name TEXT,                       -- Mode where command runs
    command_id INTEGER,                   -- Reference to actual command
    command_text TEXT,                    -- If not in commands table
    explanation TEXT NOT NULL,            -- Why this step?
    expected_result TEXT,                 -- What indicates success/failure?
    interpretation_guide TEXT,            -- How to interpret output
    next_step_logic TEXT,                 -- JSON: conditional next steps
    FOREIGN KEY (workflow_id) REFERENCES cli_workflows(workflow_id) ON DELETE CASCADE,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id)
);

CREATE INDEX idx_workflow_steps_workflow_id ON cli_workflow_steps(workflow_id);
CREATE INDEX idx_workflow_steps_command_id ON cli_workflow_steps(command_id);

-- ============================================================================
-- Command Relationships Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_command_relationships (
    rel_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    related_command_id INTEGER NOT NULL,
    relationship_type TEXT NOT NULL,      -- "requires", "conflicts", "related", "alternative", "verification"
    description TEXT,                     -- Explain the relationship
    sequence_order INTEGER,               -- If there's a typical order
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE,
    FOREIGN KEY (related_command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE
);

CREATE INDEX idx_cmd_rel_command_id ON cli_command_relationships(command_id);
CREATE INDEX idx_cmd_rel_type ON cli_command_relationships(relationship_type);

-- ============================================================================
-- Command Warnings / Gotchas Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_command_warnings (
    warning_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    warning_type TEXT NOT NULL,           -- "data_loss", "outage", "memory_intensive", "deprecation"
    severity TEXT NOT NULL,               -- "critical", "warning", "info"
    message TEXT NOT NULL,                -- The warning message
    mitigation TEXT,                      -- How to avoid the issue
    affects_version TEXT,                 -- EOS version if relevant
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE
);

CREATE INDEX idx_cmd_warnings_command_id ON cli_command_warnings(command_id);
CREATE INDEX idx_cmd_warnings_severity ON cli_command_warnings(severity);

-- ============================================================================
-- Command Usage Statistics (for identifying top commands)
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_command_stats (
    stat_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    view_count INTEGER DEFAULT 0,        -- How many times viewed
    insert_count INTEGER DEFAULT 0,      -- How many times inserted to configlet
    favorite_count INTEGER DEFAULT 0,    -- How many users favorited
    last_accessed TIMESTAMP,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE,
    UNIQUE(command_id)
);

CREATE INDEX idx_cmd_stats_command_id ON cli_command_stats(command_id);
CREATE INDEX idx_cmd_stats_views ON cli_command_stats(view_count DESC);

-- ============================================================================
-- User Favorites / Bookmarks
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_user_favorites (
    favorite_id INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id INTEGER NOT NULL,
    user_id TEXT,                         -- Username or session ID
    notes TEXT,                           -- User's personal notes
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (command_id) REFERENCES cli_commands(command_id) ON DELETE CASCADE
);

CREATE INDEX idx_user_favorites_command ON cli_user_favorites(command_id);
CREATE INDEX idx_user_favorites_user ON cli_user_favorites(user_id);

-- ============================================================================
-- Learning Paths
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_learning_paths (
    path_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,                  -- "BGP Configuration Mastery"
    description TEXT,
    skill_level TEXT DEFAULT 'beginner', -- "beginner", "intermediate", "advanced"
    category TEXT,                        -- "Routing", "Switching", "Security"
    estimated_duration TEXT,              -- "2-3 hours"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Learning Path Modules
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_learning_modules (
    module_id INTEGER PRIMARY KEY AUTOINCREMENT,
    path_id INTEGER NOT NULL,
    module_number INTEGER NOT NULL,
    title TEXT NOT NULL,                  -- "Module 1: Basic BGP Setup"
    description TEXT,
    content TEXT,                         -- Markdown content
    commands TEXT,                        -- JSON array of command_ids
    lab_scenario TEXT,                    -- Practice lab description
    quiz_questions TEXT,                  -- JSON array of quiz questions
    FOREIGN KEY (path_id) REFERENCES cli_learning_paths(path_id) ON DELETE CASCADE
);

CREATE INDEX idx_learning_modules_path ON cli_learning_modules(path_id);

-- ============================================================================
-- Migration Metadata
-- ============================================================================
CREATE TABLE IF NOT EXISTS cli_migrations (
    migration_id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(migration_name)
);

INSERT INTO cli_migrations (migration_name) VALUES ('add_documentation_tables_v1');

-- ============================================================================
-- Views for Easy Querying
-- ============================================================================

-- View: Commands with documentation status
CREATE VIEW IF NOT EXISTS v_commands_with_docs AS
SELECT
    c.command_id,
    c.mode_id,
    c.command_text,
    c.command_base,
    m.mode_name,
    m.mode_category,
    d.doc_id,
    d.short_description,
    d.ai_generated,
    d.reviewed_by,
    CASE
        WHEN d.doc_id IS NULL THEN 'undocumented'
        WHEN d.reviewed_by IS NOT NULL THEN 'reviewed'
        WHEN d.ai_generated = 1 THEN 'ai_generated'
        ELSE 'documented'
    END as doc_status,
    COALESCE(s.view_count, 0) as views,
    COALESCE(s.favorite_count, 0) as favorites
FROM cli_commands c
JOIN cli_modes m ON c.mode_id = m.mode_id
LEFT JOIN cli_command_docs d ON c.command_id = d.command_id
LEFT JOIN cli_command_stats s ON c.command_id = s.command_id;

-- View: Top commands by category
CREATE VIEW IF NOT EXISTS v_top_commands_by_category AS
SELECT
    m.mode_category,
    c.command_base,
    COUNT(c.command_id) as variant_count,
    MAX(COALESCE(s.view_count, 0)) as max_views,
    m.mode_name
FROM cli_commands c
JOIN cli_modes m ON c.mode_id = m.mode_id
LEFT JOIN cli_command_stats s ON c.command_id = s.command_id
GROUP BY m.mode_category, c.command_base, m.mode_name
ORDER BY max_views DESC;

-- ============================================================================
-- Sample Data Insert: Common Parameters
-- ============================================================================

INSERT OR IGNORE INTO cli_parameter_docs (parameter_name, description, data_type, examples) VALUES
    ('PREFIX', 'IPv4 network prefix in CIDR notation', 'ipv4-prefix', '["10.0.0.0/8", "192.168.1.0/24", "172.16.0.0/16"]'),
    ('PREFIX6', 'IPv6 network prefix in CIDR notation', 'ipv6-prefix', '["2001:db8::/32", "fe80::/10"]'),
    ('ADDR_FAMILY', 'BGP address family type', 'enum', '["ipv4 unicast", "ipv6 unicast", "evpn", "vpnv4", "vpnv6"]'),
    ('ASN', 'Autonomous System Number', 'integer', '["65000", "64512", "4200000000"]'),
    ('IP_ADDR', 'IPv4 address', 'ipv4-address', '["10.1.1.1", "192.168.1.254"]'),
    ('IPV6_ADDR', 'IPv6 address', 'ipv6-address', '["2001:db8::1", "fe80::1"]'),
    ('INTERFACE', 'Interface name', 'string', '["Ethernet1", "Management1", "Loopback0"]'),
    ('VLAN_ID', 'VLAN identifier', 'integer', '["10", "100", "4094"]');

-- ============================================================================
-- Success Message
-- ============================================================================

SELECT 'Migration completed successfully!' as status,
       (SELECT COUNT(*) FROM cli_command_docs) as documentation_entries,
       (SELECT COUNT(*) FROM cli_parameter_docs) as parameter_entries,
       (SELECT COUNT(*) FROM cli_workflows) as workflow_entries;
