#!/usr/bin/env python3
"""
SwixBuilder — generates the Kármán device-resident agent script and .swix extension.

The agent runs as an EOS daemon on the switch.  It periodically checks in with Kármán
to report it is alive and, on request, pushes a backup of the running configuration.

.swix format: a ZIP archive containing:
  manifest           — plain-text metadata (EOS reads this)
  usr/bin/karman_agent.py — the agent script
"""

import io
import time
import zipfile


# ---------------------------------------------------------------------------
# Agent script template
# Placeholders use __UPPER__ style — no curly braces → no f-string conflicts.
# ---------------------------------------------------------------------------
_AGENT_SCRIPT = r'''#!/usr/bin/env python3
# =============================================================================
# Kármán Device Agent  v1.0
# Runs as EOS daemon — checks in with Kármán every __INTERVAL__ seconds.
# Auto-generated by Kármán on __GENERATED_AT__
# =============================================================================
import json
import os
import subprocess
import time
import urllib.request
import urllib.error

KARMAN_URL  = "__KARMAN_URL__"
API_KEY     = "__API_KEY__"
HOSTNAME    = ""          # populated at runtime
INTERVAL    = __INTERVAL__
RETRY_DELAY = 30


def log(msg):
    print(f"[karman-agent] {msg}", flush=True)


def run_cli(*commands):
    """Run one or more EOS CLI commands and return stdout."""
    try:
        result = subprocess.run(
            ["FastCli", "-p", "15", "-c", "\n".join(commands)],
            capture_output=True, text=True, timeout=30,
        )
        return result.stdout.strip()
    except Exception as e:
        log(f"CLI error: {e}")
        return ""


def get_hostname():
    out = run_cli("show hostname")
    for line in out.splitlines():
        line = line.strip()
        if line and not line.lower().startswith("fqdn"):
            return line.split()[-1]
    import socket
    return socket.gethostname()


def get_serial():
    out = run_cli("show version | include Serial")
    for line in out.splitlines():
        if "Serial" in line:
            parts = line.split()
            if parts:
                return parts[-1]
    return ""


def get_mgmt_ip():
    out = run_cli("show management interface")
    for line in out.splitlines():
        if "Internet address" in line:
            return line.split()[-1].split("/")[0]
    return os.environ.get("DHCP_IP", "")


def checkin(hostname, ip, serial, event="heartbeat"):
    if not KARMAN_URL or not API_KEY:
        log("KARMAN_URL or API_KEY not set — skipping check-in")
        return False
    payload = json.dumps({
        "hostname": hostname,
        "ip":       ip,
        "serial":   serial,
        "event":    event,
        "api_key":  API_KEY,
    }).encode()
    req = urllib.request.Request(
        f"{KARMAN_URL}/api/devices/checkin",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
            if result.get("success"):
                log(f"Check-in OK ({event})")
                return True
            log(f"Check-in rejected: {result.get('message', 'unknown')}")
            return False
    except Exception as e:
        log(f"Check-in failed: {e}")
        return False


def detect_config_loss():
    """
    Return True if the running config looks like a factory reset.
    Heuristic: running-config has fewer than 20 lines.
    """
    out = run_cli("show running-config")
    lines = [l for l in out.splitlines() if l.strip() and not l.strip().startswith("!")]
    return len(lines) < 20


def main():
    global HOSTNAME
    log("Starting — connecting to " + (KARMAN_URL or "(no URL set)"))

    HOSTNAME = get_hostname()
    ip       = get_mgmt_ip()
    serial   = get_serial()

    log(f"Device: {HOSTNAME}  ip={ip or '?'}  serial={serial or '?'}")

    # Startup check-in
    checkin(HOSTNAME, ip, serial, event="startup")

    tick = 0
    while True:
        time.sleep(INTERVAL)
        tick += 1

        # Refresh IP (DHCP may change)
        ip = get_mgmt_ip()

        # Detect config loss (factory reset / write erase)
        if detect_config_loss():
            log("Config loss detected — notifying Kármán")
            checkin(HOSTNAME, ip, serial, event="config_lost")
        else:
            checkin(HOSTNAME, ip, serial, event="heartbeat")


if __name__ == "__main__":
    main()
'''

# ---------------------------------------------------------------------------
# .swix manifest template
# ---------------------------------------------------------------------------
_MANIFEST = """\
Format: 1
Name: karman-agent
Version: 1.0
Release: 1
Architecture: noarch
Description: Kármán device-resident check-in agent
"""


class SwixBuilder:
    """Generates the Kármán agent script and .swix file."""

    DEFAULT_INTERVAL = 300  # seconds between check-ins

    def generate_agent_script(self, karman_url: str, api_key: str,
                               interval: int = DEFAULT_INTERVAL) -> str:
        """Return the agent Python script as a string."""
        script = _AGENT_SCRIPT
        script = script.replace('__KARMAN_URL__', karman_url.rstrip('/'))
        script = script.replace('__API_KEY__', api_key)
        script = script.replace('__INTERVAL__', str(interval))
        script = script.replace('__GENERATED_AT__',
                                time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime()))
        return script

    def generate_swix(self, karman_url: str, api_key: str,
                      interval: int = DEFAULT_INTERVAL) -> bytes:
        """
        Return a .swix ZIP file (bytes) containing the manifest and agent script.
        EOS stores the file at /mnt/flash/karman-agent.swix after 'copy ... flash:'.
        Install with: extension karman-agent.swix
        Persist with: copy installed-extensions boot-extensions
        """
        script = self.generate_agent_script(karman_url, api_key, interval)
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
            zf.writestr('manifest', _MANIFEST)
            zf.writestr('usr/bin/karman_agent.py', script)
        return buf.getvalue()
